### ISSUE TITLE
Ability to use Tesseract on other versions of Windows, not just Windows 10

### ISSUE THREAD

**Issue by DraganRatkovich** [mush42/bookworm#109]
This is not a Bookworm problem, so the paragraph with the problem has been removed, instead it's a feature request that, on reflection, would be really useful.
Bookworm currently supports Windows 10 built-in OCR, as well as the free Tesseract engine, which is very handy, as it supports a wide range of languages, including Georgian, etc.
The Bookworm OCR feature can only be used on Windows 10 and up, and this is understandable, since this feature is only built into Windows 10 and up, however, the same cannot be said for Tesseract, because it is an independent engine from Windows 10's built-in OCR engine and can be downloaded as an installable engine on Bookworm just like on Windows 10, but for use on other versions of Windows, such as 8.1, 7 and etc.
## Describe alternatives you've considered
If possible, please make the download of the Tesseract engine available for other versions of Windows as well, because I know blind people, who still use Windows 8.1 as their main operating system and run Bookworm without any problems, so the OCR engine would really be useful if Tesseract would be available on Windows 8.1, 7 and personally I use Windows 8.1 as my second operating system with Windows 10 and I really enjoy working with it and every time I need to scan something with Bookworm, I have to switch on Windows 10 and go back to 8.1 if necessary.
@mush42 @TheQuinbox Not sure how it's possible to make Tesseract available for use on versions of Windows earlier than 10, but please, let me know your thoughts.

**Comment by mush42** [comment]
Tesseract OCR engine download should be available unconditionally. So it is a bug, not a feature, if tesseract download is disabled for any version of windows.

**Comment by DraganRatkovich** [comment]
@mush42 On Windows 8.1, I can't find the OCR section in the settings to be able to load Tesseract, even the OCR setting is not available in the Alt menu. Do you know how to install Tesseract on Bookworm on Windows 8.1?

**Comment by mush42** [comment]
@DraganRatkovich 

Now that this issue has been fixed, I have an unrelated question: does Bookworm run well on Windows 7? since it is an unsupported platform by Bookworm, Python, Microsoft..etc.

Best
Musharraf

**Comment by cary-rowen** [comment]
I found someone to test the situation with Windows7SP1, using the portable version:
The following errors are reported:
This program cannot be started because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try to reinstall the program to resolve this issue.

**Comment by DraganRatkovich** [comment]
@cary-rowen If the issue occurs when running Bookworm, then you need to install the Visual C++ Redistributables from 2005 to 2022, both X32 and X64 bit versions. Download them from [here](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist)

**Comment by mush42** [comment]
@DraganRatkovich  does Bookworm work correctly after installing the c++ redistributables?

**Comment by cary-rowen** [comment]
Hi,

If we use python3.9 then maybe Win7 is not supported.
but i will test it.

Thanks

**Comment by DraganRatkovich** [comment]
@mush42 Yes, it opens without problems. Last time I was missing my C++ Redistributables on the system and I had the same .dll errors. Also, the .NET Framework must be installed on the system, but I don't remember which version is the latest supported on Windows 7.

**Comment by DraganRatkovich** [comment]
@mush42 Also, can you build a portable version from the new commits for me? Because I don't know when the update will be released and there are a lot of changes that I really want to test so I have to deal with Visual Studio etc to build and I'm not even sure if it will be successful or no.

**Comment by DraganRatkovich** [comment]
@mush42 Yes, the link works, but I downloaded now and the settings menu does not activate. When I click, the interface just goes to the main menu, nothing else and please take a look at it. I think this is due to the last change to OCR when you made it available for download on other versions of Windows

**Comment by cary-rowen** [comment]
Hi @mush42 

I am sorry for being off topic, can I use info@blindpandas.com to get in touch with you privately?

Thanks

**Comment by mush42** [comment]
@DraganRatkovich  please provide the log of the failed run.

**Comment by mush42** [comment]
@cary-rowen  please use the following email address:
musharraf.omer@gmail.com

**Comment by DraganRatkovich** [comment]
@mush42 There are no errors on startup it just doesn't show the settings window and the log doesn't show anything about it.

**Comment by DraganRatkovich** [comment]
@mush42 Also, I regret to say that .txt files that are in Georgian with UTF-8 and larger than 1mb still open very slowly.

**Comment by mush42** [comment]
@DraganRatkovich  would you mind sending me one of those plane text files. I cannot debug without directly testing with the document causing the issue.

**Comment by DraganRatkovich** [comment]
@mush42 Of course, I will send it to the email address you provided here, but please note the problem with the preferences.

**Comment by DraganRatkovich** [comment]
@mush42 I sent you a text file, and also, I want to note that I converted this text to Latin, and the document opened in just seconds, while the original Georgian version opens very slowly. Not sure what is the problem.

**Comment by DraganRatkovich** [comment]
@mush42 Okay, I see a few changes being made, hopefully the builds will be available soon via the link provided.

**Comment by mush42** [comment]
@DraganRatkovich  the builds usually take about 20 to 25 minutes for each commit.

**Comment by DraganRatkovich** [comment]
@mush42 Did you manage to solve the problem with the .txt file?

**Comment by cary-rowen** [comment]
Hi @DraganRatkovich 
Windows 7 has installed the above runtime library, but it still doesn't seem to work.
Thanks

**Comment by DraganRatkovich** [comment]
Hello @cary-rowen Please check them if they are installed correctly or not, because when I installed it from a third party source, even the name of the C++ redistributable was correct, but the dll errors were still flying around the system. Let me know what versions and with what exact names they are installed on the mentioned system.

**Comment by cary-rowen** [comment]
@DraganRatkovich 
Hi, I'll check further, but if bookworm is built with python 3.9, does that mean windows7 won't work?
Do you have any successful experience running on windows7?

Thanks

**Comment by cary-rowen** [comment]
I got errors reported by others as follows:
Error loading Python DLL 'C:\Bookworm-2022.1a5-x64-portable\Bookworm-2022.1a5-x64-portable\python39.dll'.
LoadLibrary: 找不到指定的模块。
