### ISSUE TITLE
The content of the "About" dialog is not localized

### ISSUE THREAD

**Issue by k-kolev1985** [mush42/bookworm#11]
## Describe the Problem

Bug: The content of the "About" dialog is not localized. Instead, the content is displayed in english. The string for it is available in the .po file. It is the "bookworm/gui/book_viewer/menubar/__init__.py:44" one and it is localized/translated. But the program ignores it for some reason and displays the english string instead. I've managed to reproduce the issue with both bulgarian and arabic translation.

## To Reproduce

1. Open Bookworm.
2. Open its preferences and change the language to something other than english (I've managed to reproduce the issue with both bulgarian and arabic translation).
3. Apply the changes with the "OK" button and restart Bookworm when prompted to do so.
4. When Bookworm restarts, from the "Help" menu, open the "About" dialog.
5. Notice how no matter that the display language is different than english, the content of the "About" dialog is still in english.

## Expected behavior

Even though the display language of Bookworm is different than english, the content of the "About" dialog is still in english.

## Desktop (please complete the following information):

 - Operating system: Windows 10 Pro version 1903 (build 18362.329), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: 0.1b2, x86 (32-bit).

**Comment by k-kolev1985** [comment]
The test build that you've provided in #6 solves this issue for the arabic language, but not for the bulgarian one. Do I need to update the bulgarian translation?

**Comment by mush42** [comment]
Yes, you need to update that. The updated catalog is already up.
The Arabic one I did my self to test the change, but you can delay the submission of the Bulgarian translation for a little while. We may need to update some other strings in the meantime.
