### ISSUE TITLE
present of '-' in pdf document

### ISSUE THREAD

**Issue by wilsonad32** [mush42/bookworm#15]
I've use bookworm to read a pdf file. For unknown reason, there are '-' symbol all over the text in the pdf document. 
E.G: 
normal text: Tax break enable more jobs created. 
What happened: Tax br- eak enable m- ore job - s cr- eated. 

When i try to open the same document using other app like adobe reader or any other apps, the text or sentences appear just fine/normal. Hopes can investigate.

**Comment by mush42** [comment]
Hi @wilsonad32,
If possible, could you send me the document with which this issue occurs.
Otherwise, I can not see whats going on, as Bookworm works well with my test documents.

**Comment by wilsonad32** [comment]
ya, it only happened on this particular file so far. I'm also curious. But, the file contains confidential materials, so i don't think it is possible to share it here. I'm Sorry for that. 

i think, for the moment, just close this issue first till i or someone else experience the same issue on other document or file which can be shared and investigated. 

Thank you.

**Comment by mush42** [comment]
OK. Closing this for now.

**Comment by mush42** [comment]
blocked by pymupdf/PyMuPDF#364
