### ISSUE TITLE
Support OneCore Voices

### ISSUE THREAD

**Issue by Simon818** [mush42/bookworm#16]
## Is your feature request related to a problem? Please describe.
No, although ability to continuously read with a screen-reader would make it less important (see below).
## Describe the solution you'd like
Support OneCore voices and allow the user to switch to them using speech settings or voice profiles.
## Describe alternatives you've considered
1. There are registry hacks to make OneCore voices available as SAPI5 voices, but this requires a certain degree of technical knowledge as well as knowledge of the possibility.
2. Narrator, NVDA and (I think) JAWS all support these voices. Since Narrator comes with Windows, one option is to just read books using Narrator or the user's preferred screen-reader along with the preferred voice. However, this is impractical right now because the screen-reader stops reading at the end of the page due to the text view only showing one at a time. If this is not something that will change, the only way to read continuously is to use the play function in Bookworm, and therefore Bookworm's voice support defines the reading experience.
## Additional context
Microsoft has a lot of really good, multilingual voices that come with Windows 10, but they are out of reach for most apps that only support SAPI 5. It would be great to see support for these voices added to Bookworm itself, so the user can make voice profiles with them and read using all available voices.

**Comment by mush42** [comment]
You're reading my mind.
The idea of supporting one-core voices in Bookworm is nagging at me for a week or so. And I've already started investigating ways to access them through .NET ABIs. No success up till now, but I'm not losing hope. As a last resort, we can use the same dll NVDA uses to access one-core voices.

**Comment by Simon818** [comment]
That's great to hear! I talked to a friend recently about the technical challenge of supporting them; they really don't make it easy. I seem to remember him finding that a DLL was the only way. Thanks for your time and the work you put into this app.

**Comment by mush42** [comment]
Good news: support for one-core speech engine seams feasible. In fact a very basic working implementation has just been pushed to the repo. I'm not promising anything here, but this issue is about to be closed!

**Comment by mush42** [comment]
Hi @Simon818 

I've created a try build with experimental support for one-core synthesizer. Please install the try build and give your feedback.

Release URL: https://github.com/mush42/bookworm/releases/tag/Bookworm-Release-(Build-v1.0.263)

Regards,
