### ISSUE TITLE
setting to change hotkey

### ISSUE THREAD

**Issue by wilsonad32** [mush42/bookworm#17]
I would like to suggest that adding a option under preferences or settings to enable users to change hotkey to particular function. For example, i prefer using screen reader instead of built-in tts to read file in bookworm. As a result, i would frequently use the standard reading command like homekey to move to the beginning of line, and end key to move to the end of line. But, these hotkeys have been assigned to move to beginning of document and end document. Therefore, i would very hopeful that such settings exist because it is quite frustrated. 

Thank you.

**Comment by k-kolev1985** [comment]
I second that. We need to either have the ability to customize the keyboard commands of Bookworm, or have ones by default that do not conflict with standard navigation and text manipulation commands. Preferably - both.

For example, a few days ago I was trying to select a line of text from its beginning. I pressed HOME to go to the beginning of the line, but instead Bookworm navigated to the first page in the current section of the opened book - definitely not what I've wanted. :-)

At least change the current commands for going to the first and last page of the current section from HOME and END to for example ALT+HOME and ALT+END, respectively. I don't think ALT+HOME and ALT+END are used in standard text navigation and therefore there should be no conflicts.

**Comment by mush42** [comment]
You're right. This is a priority fix. Sorry for any inconveniences.
