### ISSUE TITLE
clear list under recent books submenu

### ISSUE THREAD

**Issue by wilsonad32** [mush42/bookworm#18]
Hi, here's another suggestion. I would like to suggest that the 'clear list' option put in the bottom of the menu instead of the first menu item. This is partly because, i think, there is less often that a user would want to clear list compared to looking for the recent books. And the second, there is a tendency to accidentally press enter on it (clear list) as usually would expect the most recent book. 

Thank you.

**Comment by mush42** [comment]
The recent files list is inspired by Notepad-plus-plus. In that program, the clear recent files list is placed on the top of the menu.

**Comment by wilsonad32** [comment]
Oh i see. but, what do you mean by top of the menu? In notepad++, recent files are listed under file menu. The first item is new followed open etc. Still, recent files list still considered bottom of the menu. 

Btw, that is only my suggestion.

**Comment by k-kolev1985** [comment]
Actually, in Notepad++, the "Recent Files" menu is almost on the bottom of the "File" menu. In the submenu of the "Recent Files" menu, the command to clear the list is on top of the list of recent files, together with two other commands.

**Comment by wilsonad32** [comment]
ya, you are right.

**Comment by mush42** [comment]
What @k-kolev1985 said is what I mean. The item for "Clear recent files" is placed at the top of the "Recent files" menu. As you said, the "Recent files" menu it self is placed near the bottom of the "File" menu.
At the end of the day, the placement of items in a menu is a matter of preference. And if there is a standard, it would be better to save ourselves the effort and stick to the standard. As you know we can not please everybody.

Pardon me, I'm going to close this issue for now. If it ever gained traction, I guarantee you I will reopen it.
