### ISSUE TITLE
Distribute portable version

### ISSUE THREAD

**Issue by cartertemm** [mush42/bookworm#2]
## Is your feature request related to a problem? Please describe.

No.

## Describe the solution you'd like

I believe it would be beneficial to additionally include portable distributions along-side the provided installers.

## Additional context

Some users might want to carry the app around on removable media or avoid having to deal with windows installers altogether.

**Comment by mush42** [comment]
Hi @cartertemm,

Thanks for your time and effort.

I agree with this suggestion. One can readily  identify more than two scenarios in which portable versions make sense.

I'v a few questions for you, as I'm not so familiar with this mode of distribution:

1. Is there any specialized format for portable applications? Or we can just use zip files?
2. What about the download size? In a zip archive, Bookworm is about 50 MB. Is this size feasible?
3. Could we just use NVDA's approach of allowing the users to create a portable version out of an installed version? although we couldn't allow the reverse (installing from a portable version).

**Comment by cartertemm** [comment]
Hello,
There isn't necessarily a specialized format per se, most people simply zip a copy of the executable along with readme, docs, and other assets when necessary. Just as long as no files are written above the current working directory. Since one would most likely be carrying around the app, it would only make sense to save configuration data some place where it wouldn't persist.

NVDA only has the option to create a portable version because it would like to account for add-ons and other user-specific configuration data which may be located in different places across the machine. Personally I say an additional file would be better, obtainable from the main page next to the installer. I suppose it doesn't really matter one way or the other though.
