### ISSUE TITLE
Display not only the title of the book in the Bookworm's title bar, but the name of the author as well.

### ISSUE THREAD

**Issue by k-kolev1985** [mush42/bookworm#21]
## Describe the solution you'd like

In bookworm's title bar, display not only the book's name, but the name of its author as well. That will make it easier to know which is the author of the current book and copy both the name of the book and the name of the author, without needing to navigate to the beginning or the end of the book to copy them from there.

**Comment by mush42** [comment]
Currently, we do this with books for which we can determine the author. Nearly all ePub documents. There is no way we can do this for all PDFs.

**Comment by k-kolev1985** [comment]
Am I to understand, that in general it should work at least for most EPUB files? Because I've tried with a few EPUB files that I have and it displays only the title for them, but not the author. I can send you privately or attach some files here for you to look at. Almost all of them are in bulgarian/cyrillic mind you, but still I think you'll manage to analyze them (and I can assist you, if needs be).

**Comment by mush42** [comment]
Oh. It was a stupid bug. Now it is fixed.
The functionality is there, but it is turned-off by a flag.
