### ISSUE TITLE
The icons for the Bookworm preferences categories are invisible if their pane has a black background

### ISSUE THREAD

**Issue by k-kolev1985** [mush42/bookworm#22]
## Describe the Problem

If the pane in which is located the list of categories in Bookworm's preferences has a black background (e.g. the "High Contrast Black" theme in Windows is used), each icon is not visible, unless its category is selected/highlighted.

## To Reproduce

1. Go to Windows Settings (press Windows+I) -> Ease of Access -> High Contrast -> Enable High Contrast.
2. From the list of themes to use for high contrast, select "High Contrast Black" - it is the one which uses black backgrounds.
3. Open Bookworm.
4. Open Bookworm's preferences.
5. Observe how the icons for the categories in the pane on the left are not visible, unless the category in question is selected/highlighted.

## Expected behavior

The icons for the categories in the pane on the left should be visible, no matter if the category in question is selected/highlighted or not.

## Desktop (please complete the following information):

 - Operating system: Windows 10 Pro version 1903 (build 18362.388), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: 0.1b3, x86.

## Additional context

The problem is a minor one. As far as I know, it is probably hard, if not impossible to fix, unless different sets of icons are used in accordance with the background color of the pane, which I think is an overkill for such a minor bug. But I'm reporting it just in case I'm wrong about its complexity and for the sake of completeness/thoroughness.

**Comment by mush42** [comment]
Hi @k-kolev1985 ,

This issue is now resolved. Also, high contrast is now taken into consideration when rendering the book.

Please raise any issues you've noticed regarding high contrast and Bookworm.

Regards,
