### ISSUE TITLE
Visually overlapping pages in rendered view in Bookworm

### ISSUE THREAD

**Issue by k-kolev1985** [mush42/bookworm#29]
## Describe the Problem

**NOTE:** I might be wrong, but I think that at least some vision may be required, in order to properly reproduce and diagnose this issue.

In Bookworm 07122019 (the test version), pages in rendered view seam to overlap vertically. The first displayed page is OK - it is centered on the screen. Each next page however has its top edge snapped to the top edge of the screen. At the same time, the next page is also displayed so its bottom edge is snapped to the bottom edge of the screen. The current page is displayed completely and the next page has its top part hidden behind the current page (probably because there is not enough vertical space to fit both). If I'm not wrong, Bookworm should display only one page at a time, so its current behavior is a bug.

## To Reproduce

1. Open Bookworm.
2. Open a book (the file format seams not to matter).
3. Execute the "Render page" function (pressing Control+R will do it).
4. Move forward and backward through the pages in the book.
5. Observe how after the first displayed page, Bookworm tries to display two pages at the same time one below the other, but probably due to not enough vertical space, the current page will overlap the next one.

## Expected behavior

Bookworm should display only one page at a time, centered on the screen and maximized for best vertical fit.

## Desktop (please complete the following information):

 - Operating system: Windows 10 Pro version 1909 (build 18363.476), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: Bookworm 07122019 (the test version).

**Comment by mush42** [comment]
t

**Comment by mush42** [comment]
Hi @k-kolev1985,

I think the regression has been fixed in the above commit. Nevertheless I'll send you a copy for testing as soon as I get a stable internet connection.

Thanks for reporting the issue.

Regards,
