### ISSUE TITLE
Bookworm inserts a "comma" character between pages when reading

### ISSUE THREAD

**Issue by k-kolev1985** [mush42/bookworm#34]
## Describe the Problem

I don't know if it is intentional or not, but Bookworm seams to be inserting a "comma" (,) character between pages. The comma character is not visible on the end or the beginning of a page, but when reading aloud with Bookworm, it can be observed that something is read between the pages - something, that is not part of the text of the loaded file. Depending on the speed of the TTS engine being used, it may be missed, but it is still there. At first I was wondering what it is, but last night I was reading a book that had a few consecutive blank pages and was able to recognize the thing that the TTS engine was trying to read between the pages. It was trying to say "comma", but since the bulgarian word for "comma" is long, in most cases the TTS engine was barely able to pronounce the first syllable from the 3-syllable bulgarian word for "comma", before it gets interrupted and forced to read the next page of the book. Last night however, when reading those few blank pages, it managed to read almost the whole bulgarian word for "comma", so I was able to understand what it was trying to say/read. Strangely enough, I don't hear the "comma" character being read while reading the book with the screen reader - only when reading it with Bookworm directly.

Actually, now that I think of it, the insertion of the "comma" character may not be between every two pages, but only in certain circumstances. But what are those certain circumstances - I haven't figured out yet.

So, is it intentional? Is Bookworm intentionally inserting the "comma" (,) character between the pages and sending it to the TTS engines while reading aloud? And if so - why it is doing it? Or is it just a bug?

## To Reproduce

1. Launch Bookworm.
2. Load a book.
3. Start reading aloud the book with Bookworm.
4. Observe how in some cases, Bookworm inserts a "comma" character between pages and sends it to the TTS engine for reading/interpretation.

## Expected behavior

Bookworm should not insert such characters that are not present in the loaded book, unless it is absolutely necessary.

## The File You've Opened

The file seams not to matter.

## Desktop (please complete the following information):

 - Operating system: Windows 10 Pro version 1909 (build 18363.535), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: 0.1b4, 32-bit, in bulgarian.

**Comment by mush42** [comment]
Hi @k-kolev1985,

I congratulate you on your intricate ability to pay attention.
Yes, Bookworm inserts commas between pages when sending speech prompts to SAPI(5).
The reason is a bug in SAPI(5), The bug prevents the synthesizer from raising the Bookmark event if it is the last element of a speech prompt, so we need to insert something after the Bookmark.

Regards,

**Comment by mush42** [comment]
The bug happens with some voices, e.g. Nuespeech  voices. So the comma is inserted as a preventive measure. Otherwise the page would not be turned.

I know that is a hacky way to do it, but I'm being pragmatic.
Regards,
