### ISSUE TITLE
El renderizado de página no responde

### ISSUE THREAD

**Issue by jerdanlat** [mush42/bookworm#35]
## Describe the Problem

Cuando intento renderizar una página, no renderiza, y NVDA dice: "página renderizada (no responde)". Luego, abre el diálogo que dice que si cierra el programa, se podría perder información, y las dos opciones: esperar a que el programa responda, o cerrar el programa.

## To Reproduce

1. Abre el programa.
2. Abre un libro epub.
3. Elige una página que sepas que contiene enlaces o imágenes.
4. Pulsa Control más R.
5. Ve el error.

## Expected behavior

Simplemente, esperaba que renderizara la página. Esto ocurre tanto en modo normal como en modo depuración, sin devolver un mensaje de error ni código.

## The File You've Opened

sucede con todos los archivos formato Epub.

## Desktop (please complete the following information):

 - OS: Windows 10 32-bit
 - Bookworm version 0.1b4.

**Comment by mush42** [comment]
I could not understand anything of the above. Actually, I do not even know what language it is written in.

Please translate it into English.

**Comment by jerdanlat** [comment]
Comments @ jerdanlatAdd your reactionShow optionsjerdanlatcommented 3 days agoDescribe the ProblemWhen I try to render a page, it does not render, and NVDA says: "page rendered (does not respond)". Then, open the dialog that says that if you close the program, you could lose information, and the two options: wait for the program to respond, or close the program.To Play1. Open the program 2. Open a book epub. 3. Choose a page you know that contains links or images. 4. Press Control plus R.5. See the error. Expected behavior I just expected you to render the page. This happens both in normal mode and in debug mode, without returning an error message or code. The File You've Opened happens with all files format Epub.Desktop (please complete the following information): • OS: Windows 10 32-bit • Bookworm version 0.1b4.
