### ISSUE TITLE
Contents of "pre" tag is rendered like one long line

### ISSUE THREAD

**Issue by lpintes** [mush42/bookworm#36]
Open an e-book in epub format containing the "pre" tag. I tested this with the book Mastering Go, second edition from Packpub. Every presented code example was rendered like one long line. This makes the book unusable, at least for me.

**Comment by mush42** [comment]
Hi @lpintes,

The issue of EPUB text extraction is known to me. I'm trying to find a time to rewrite the text extraction functions to make them more robust.

Related issue: #24 
Regards,

**Comment by mush42** [comment]
Duplicate: #24
