### ISSUE TITLE
Can you add documents for language translates?

### ISSUE THREAD

**Issue by SeanTolstoyevski** [mush42/bookworm#38]
Hello, I would like to add the Turkish language to this beautiful program.
But there is no POT file.
A simple translation document is very useful.
I don't know how to prepare the translation template without a POT file.
I'm going to try something with PoEdit.

How should I proceed with the process of adding new translations?

God bless all script code lines 😂🤗 .

**Comment by mush42** [comment]
Hi @SeanTolstoyevski,

Until we find a suitable, automated, translation system, everything related to translation is done manually here.

Please provide me with your email address, so that I can add you to the translators' list.

Regards,

**Comment by SeanTolstoyevski** [comment]
Great.
My mail address: seantolstoyevski@protonmail.com
