### ISSUE TITLE
Bookworm does not show the name of the voice "Irina" from Innoetics

### ISSUE THREAD

**Issue by k-kolev1985** [mush42/bookworm#6]
## Describe the Problem

There is a bulgarian SAPI5 voice, developed by the greek company "Innoetics". The voice is called "Irina". Bookworm fails to display its name in the list of available voices. Instead, it shows only a blank entry in its place. The voice works and can be used in Bookworm - only its name does not display as it should. This occurs only in Bookworm. Other programs (e.g. NVDA, JAWS, Balabolka) do see the voice correctly with its name.

Unfortunately, the company "Innoetics" does no longer distribute its voices (they can't be downloaded from their website). But I can privately send you an installer for a demo of the voice, if needs be.

If I can provide some logs in which the issue is recorded/reproduced, please let me know how to create them and from where to obtain them.

## To Reproduce

1. Install the voice "Irina" from "Innoetics" from its installer. You can use it as a demo for our purposes.
2. Open Bookworm.
3. Open the Bookworm preferences.
4. Navigate to the "Speech" section.
5. Go to the "Select Voice" combo box.
6. Open the "Select Voice" combo box with Alt+Down Arrow.
7. Use the Up/Down arrow keys to navigate between available voices.

## Expected behavior

Bookworm should see the voice "Irina" with its display name in the list of available voices.

## Desktop (please complete the following information):

 - Operating system: Windows 10 Pro version 1903 (build 18362.329), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: 0.1b2, x86 (32-bit).

**Comment by mush42** [comment]
To interface with SAPI5 we're using an approach that is different from NVDA's approach. 

If you send me the installer, I would be able to see what attributes could be used to access the voice's name.
Anyhow, I think the issue would be easy to fix.

**Comment by k-kolev1985** [comment]
I've sent you a link for it in a DM on Twitter.

**Comment by mush42** [comment]
Hi Kolev,

I've prepared a debug build for you. This build claims to resolve all the issues you've reported today, including this one.

Please download the attached file, extract it, uninstall your current version, install this one, and give your feedback.
[Bookworm-0.1b2-x86-setup.zip](https://github.com/mush42/bookworm/files/3591596/Bookworm-0.1b2-x86-setup.zip)

**Comment by k-kolev1985** [comment]
Yes, the test build solves this issue. Thanks!
