### ISSUE TITLE
For group controls in some dialogs, the first option visually overlaps the header/name of the group

### ISSUE THREAD

**Issue by k-kolev1985** [mush42/bookworm#7]
## Describe the Problem

**NOTE:** I might be wrong, but I think that at least some vision may be required, in order to properly reproduce and diagnose this issue.

In some dialogs of Bookworm, in group controls (where there are a few controls visually grouped together), the text label of the first control in the group is positioned so it is located over the name of the group. Many such examples can be found in Bookworm preferences. Exceptions in there seam to be the groups of controls that contain radio buttons - there the label of the group is visible, because the first control in the group (the first radio button) is located below it as it should and not over it.

## To Reproduce

1. Open Bookworm preferences.
2. Select any of the categories of settings.
3. Observe how in most groups of settings/options, the first option in each group is positioned on top (over) the text label for the group name, making it invisible/unreadable.

## Expected behavior

The first option in each group of options should be positioned within the group container and not on its edge, so it does not obscure the label for the group.

## Desktop (please complete the following information):

 - Operating system: Windows 10 Pro version 1903 (build 18362.329), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: 0.1b2, x86 (32-bit).

**Comment by mush42** [comment]
Cause: wxWidgets/Phoenix#974

**Comment by k-kolev1985** [comment]
Yes, the test build that you've provided in #6 solves this issue. Thanks!
