### ISSUE TITLE
In the "Bookworm File Associations" dialog, the string "Associate files of type" is not localized

### ISSUE THREAD

**Issue by k-kolev1985** [mush42/bookworm#8]
## Describe the Problem

In the "Bookworm File Associations" dialog, the string "Associate files of type" for each individual file type is not localized. Instead, it is shown in english. Only the "Associate files of type" part is not localized - the name of the file type is localized.

## To Reproduce

1. Open Bookworm.
2. Open Bookworm preferences.
3. Select the "Main" preferences category.
4. From the "Display language" combo box, choose a language other than english (I can reproduce it with bulgarian and arabic).
5. Apply the changes with the "OK" button and restart Bookworm when prompted to do so.
6. When Bookworm restarts, open the Bookworm preferences.
7. Select the "Main" preferences category.
8. Activate the "Manage File Associations" button in there. The "Bookworm File Associations" dialog opens.
9. Use TAB to navigate between the available buttons in the "Bookworm File Associations" dialog.

## Expected behavior

The "Associate files of type" string is displayed in english, even though Bookworm's display language is not english.

## Desktop (please complete the following information):

 - Operating system: Windows 10 Pro version 1903 (build 18362.329), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: 0.1b2, x86 (32-bit).

**Comment by mush42** [comment]
Already fixed in a previous commit>

**Comment by k-kolev1985** [comment]
Yes, the test build that you've provided in #6 solves this issue. Thanks!
